services:
  gateway:
    image: nginx:1.27-alpine
    ports:
      - "8088:80"
    volumes:
      - ../../mission-1-app/web-app/dist:/usr/share/nginx/html:ro
      - ../../admin/dist:/usr/share/nginx/admin:ro
      - ../server-config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backoffice
      - api-go

  backoffice:
    build:
      context: ../../mission-1-app/backoffice
      dockerfile: Dockerfile
    volumes:
      - ../../mission-1-app/backoffice/storage:/var/www/storage

  api-go:
    build:
      context: ../../mission-1-app/api-go
      dockerfile: Dockerfile
